### ISSUE TITLE
Error while injecting into Roblox

### ISSUE THREAD

**Issue by XPKNeon** [axstin/rbxfpsunlocker#61] opened 2019-06-05 23:24 UTC
When the Roblox launcher opens, the injector seems to attempt to inject into the launcher, and not the game itself. It throws this error in the console:
![image](https://user-images.githubusercontent.com/33107313/58996766-3dfced00-87bf-11e9-899f-d1fc937f3470.png)
![image](https://user-images.githubusercontent.com/33107313/58996771-41907400-87bf-11e9-8d4a-9ed73486a482.png)

BUT, if you run rbxfpsunlocker after your game is already loaded, it shows this and there's no issue. Voila!
![image](https://user-images.githubusercontent.com/33107313/58996728-19087a00-87bf-11e9-8afc-982ee27aa5f4.png)
![image](https://user-images.githubusercontent.com/33107313/58996732-1c036a80-87bf-11e9-98d4-e4de606a768a.png)

**Comment by XPKNeon** [comment] 2019-06-05 23:29
I'm assuming this is because it's trying to inject into RobloxPlayerBeta before it is actually initialized?

**Comment by KeysandLemons** [comment] 2019-06-08 08:12
How do I fix this sir. "Failed to connect to github / When after I open it and it doesnt show the long text coding"
Help?

**Comment by XPKNeon** [comment] 2019-06-08 13:16
I've got no idea

**Comment by KeysandLemons** [comment] 2019-06-08 22:05
Aight mate, Thanks!

**Comment by axstin** [comment] 2019-08-08 22:50
Version 4.1 attempts to reduce the chances of this error by retrying upon failure. Let me know if the issue persists.

**Comment by axstin** [comment] 2019-08-08 23:05
Closing this issue as a duplicate of https://github.com/axstin/rbxfpsunlocker/issues/59. Check there for updates on this issue

**Closed by axstin** 2019-08-08 23:05 UTC
