### ISSUE TITLE
when i press "/" to chat it doesnt work because of this

### ISSUE THREAD

**Issue by aguy53** [axstin/rbxfpsunlocker#116] opened 2019-11-06 17:25 UTC
so without this unlocker i was able to send mesages in chat using "/" but with the unlocker i cant,i think this is all because of the new update

**Comment by aguy53** [comment] 2019-11-06 17:32
also it works if i put it on a cap of 144 fps

**Comment by aguy53** [comment] 2019-11-06 17:34
acctually doesnt work at all

**Comment by CelestialVindication** [comment] 2019-11-06 22:48
The program doesn't break the chat, the newest update does.

This error is caused by alt-tabbing out of the game. You can fix it by hitting "ALT + /" while selecting the game window. 

Close this issue. @aguy53

**Closed** 2019-11-08 20:03 UTC
